---

matrix:
  include:
    - name: "Python 3.8"
      os: windows
      language: shell
      before_install:
        # - choco install python
        - choco install python --version 3.8.1
        # - choco install anaconda3 && conda update conda && conda update anaconda
        # - choco install anaconda3
        # - conda update --all
        # - conda info
        # - conda list anaconda$
      env:
        # - PATH=/c/Python37:/c/Python37/Scripts:/c/tools/bin:$PATH**
        - PATH=/c/Python38:/c/Python37/Scripts:/c/tools/bin:$PATH**
install:
      # Enable running local PowerShell scripts
      - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
      # pip install via choco
      # - cinst anaaconda3
      # - pip --version
      # upgrade PIP
      # - python -m pip install --upgrade pip
      # - conda install virtualenv
      # - pip install virtualenv
      # - virtualenv myenv
      # same directory
      # - myenv\Scripts\activate
      # - myenv\Scripts\activate.bat
      # - deactivate

script:
    - python --version
    - choco --version
