---
matrix:
  fast_finish: true
  include:

    - name: "Python 3.8 pinned virtual environment anaconda"
      os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
        - python3 -m pip install --upgrade pip
        # - choco install anaconda3 && conda update conda && conda update anaconda
        - choco install anaconda3
        - conda info
        - conda list anaconda$
        # - conda update --all
install:
      # Enable running local PowerShell scripts
      - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
      # pip install via choco
      # - cinst anaaconda3
      # - pip --version
      # upgrade PIP
      # - python -m pip install --upgrade pip
      # - conda install virtualenv
      # - pip install virtualenv
      # - virtualenv myenv
      # same directory
      # - myenv\Scripts\activate
      # - myenv\Scripts\activate.bat
      # - deactivate

script:
    - python --version
    - choco --version
