---
matrix:
  fast_finish: true
  include:

os: osx
language: shell
osx_image:
    - xcode9.4
    - xcode10.2
    - xcode11
    - xcode11.1
    - xcode11.2

# run tasks for all images
before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
install:
        - pip install -r requirements.txt

script:
        - pip list

after_success:
        - deactivate
